version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./dbData:/data/db
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__Host=mongo
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    container_name: api
    depends_on:
      - mongo

